site_name: Restoria
site_description: Professional face restoration powered by generative AI
site_url: https://IAmJonoBo.github.io/Restoria/
repo_url: https://github.com/IAmJonoBo/Restoria
repo_name: IAmJonoBo/Restoria
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.suggest
    - content.tabs.link
    - content.code.copy
    - content.action.edit
  icon:
    edit: material/pencil
    view: material/eye

plugins:
  - search:
      lang: en
  - mike:
      version_selector: true
      css_dir: css
      javascript_dir: js

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/IAmJonoBo/Restoria

nav:
  - Home: index.md
  - Getting Started:
    - Quick Start: getting-started/quickstart.md
    - Installation: getting-started/install.md
    - Development Environment: DEV_ENV.md
    - Run in the Cloud: getting-started/cloud.md
  - User Guides:
    - Face Enhancement: guides/face-enhancement.md
    - Batch Processing: guides/batch-processing.md
    - Choose Backend: guides/choose-backend.md
    - Auto Mode: guides/auto-mode.md
    - Metrics & Evaluation: guides/metrics.md
    - Hardware Guide: HARDWARE_GUIDE.md
    - Performance on your Hardware: guides/hardware.md
    - Notebooks: usage/colab.md
    - Migration to Restoria: guides/migration.md
    - Accessibility: ACCESSIBILITY.md
    - Troubleshooting: troubleshooting.md
    - UI Guide (Gradio): UI_GUIDE.md
    - Guided Walkthrough: guides/guided.md
    - Restore a Photo: guides/restore-a-photo.md
  - Reference:
    - CLI Usage: usage/cli.md
    - Doctor: reference/doctor.md
    - Backend Matrix: BACKEND_MATRIX.md
    - Compatibility: COMPATIBILITY.md
    - ORT Guide: ORT_GUIDE.md
    - Torch 2 Notes: TORCH2.md
    - Decision Table: DECISION_TABLE.md
    - Determinism & Seeding: reference/determinism.md
    - Manifests & Metrics: reference/manifests-and-metrics.md
    - Recipes: usage/recipes.md
    - Gradio Usage: usage/gradio.md
    - REST API Usage: usage/api.md
  - API Reference:
    - Overview: api/index.md
    - Core Functions: api/core.md
    - Models: api/models.md
    - Utilities: api/utils.md
  - Product Info:
    - Model Card: product/model-card.md
    - Data Card: product/data-card.md
    - Performance: product/performance.md
  - Governance:
    - Contributing: governance/contributing.md
    - Docs Conventions: governance/docs-conventions.md
    - Code of Conduct: governance/code-of-conduct.md
    - Privacy: governance/privacy.md
    - Ethics: governance/ethics.md
    - Security: governance/security.md
    - Maintainers: governance/maintainers.md
    - Versioning: governance/versioning.md
    - Release Playbook: governance/release-playbook.md
    - Repo rename checklist: guides/repo-rename.md
  - About:
    - FAQ: faq.md
    - Changelog: about/changelog.md
    - Acknowledgements: about/acknowledgements.md
    - License: about/license.md
    - Brand: product/brand.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.keys
  - attr_list
  - md_in_html
  - toc:
      permalink: true
      title: On this page

watch:
  - docs/
