name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests-light:
    name: Tests (light)
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      - name: Run tests_light
        run: |
          uv run --no-project --with pytest --with numpy python -m pytest -q tests_light

  docs:
    name: Docs build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      - name: Build docs
        run: |
          uv run --no-project --with mkdocs --with mkdocs-material --with mike mkdocs build --clean

  link-check:
    name: Link check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lychee link check
        uses: lycheeverse/lychee-action@v2
        with:
          args: --no-progress --exclude-mail --accept 200,403,429 --max-redirects 5 --timeout 20s './**/*.md'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  tests-heavy:
    name: Tests (heavy)
    if: github.event_name == 'push' || github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install minimal deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Optional extras, best-effort
          pip install '.[metrics,arcface,codeformer,restoreformerpp]'
          pip install pytest
      - name: Run tests
        env:
          GFPP_NO_DEPRECATION: '1'
        run: |
          pytest -q tests || true
          pytest -q tests_light
