name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11" ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install tools
        run: pip install --disable-pip-version-check --no-input ruff black

      - name: Lint (ruff)
        run: ruff check .

      - name: Format check (black)
        run: black --check .

      - name: Smoke import
        run: |
          python - <<'PY'
          import importlib
          import sys
          try:
              importlib.import_module('gfpgan')
          except Exception as e:
              # Do not fail CI while tests stabilize
              print(f"Import warning: {e}", file=sys.stderr)
          PY

  smoke:
    name: smoke (3.11)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Syntax check (compileall)
        run: |
          python -m compileall -q gfpgan scripts inference_gfpgan.py || exit 1

  links:
    name: links
    runs-on: ubuntu-latest
    steps:
      - name: Check Colab notebook link
        run: |
          URL="https://colab.research.google.com/github/IAmJonoBo/GFPGAN/blob/main/notebooks/GFPGAN_Colab.ipynb"
          code=$(curl -s -o /dev/null -w "%{http_code}" "$URL")
          echo "Colab URL status: $code"
          [ "$code" -eq 200 ]

  tests-light:
    name: tests (light)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install package (CPU)
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev,torch2]
          # Ensure Basicsr master to match latest torchvision API
          pip install --no-cache-dir --upgrade "git+https://github.com/xinntao/BasicSR@master"
      - name: Run light tests
        run: pytest -q tests_light
