name: sbom

# Secure permissions - only grant what's needed
permissions:
  contents: read

on:
  push:
    branches: [ main, master, feat/** ]
  pull_request:
    branches: [ main, master ]

jobs:
  cyclonedx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Generate SBOM (CycloneDX)
        uses: anchore/sbom-action@v0
        with:
          path: .
          output-file: sbom.cdx.json
          format: cyclonedx-json
      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.cdx.json

